global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus_router'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.1:9090']
  - job_name: 'node_exporter_router'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.1:9100']
  - job_name: 'prometheus_web'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_web'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
